apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-media
  namespace: r16a-chat
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 20Gi