apiVersion: v1
kind: Secret
metadata:
    name: synapse-signing-key
    namespace: r16a-chat
type: Opaque
stringData:
    chat.r16a.cloud.signing.key: ENC[AES256_GCM,data:rUzYgfT2olHlMmoP9mgHjlWNRMsmybSM9EcRvfNVVndXSLGyWJoOXH+XseoJf5n1+aTN6ZFQocU7pg==,iv:k8V36uhV7vMt+O4IV/FdWzqu/R8PFHpigi6n85H7vjo=,tag:3671Gitibojd88Qq9ZKqRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TCt5NFl3d3ZueU5qa2Rz
            cnB5TmYwTFlMbGNxVlphOVpOSlgrT1RZM1NrCi9PanFNMHlaRy9iVlJESHBUNEFl
            ZjBUUStrN2l4MjhJZ2pkREpaV2NDaGMKLS0tIEkxbG9RQTRFMk5xZkR5LzJKejlq
            UjVsRnFHdzV0WFhWcndtaXAxSkk5R0EKPNxe67HuQrvc2f6fg4LugLQuH+Qin8gH
            kr5XfUzOknLFPqqXbnWITBIHFBOu8v2VyP6V2hKi16HyjURJmcaY5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lgkgdrmkprkm3325ufhmd64sqgc633p069xpjrngyy4ecgrzspys407msz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T11:09:53Z"
    mac: ENC[AES256_GCM,data:l6YK6P483yfvm4s2qVAppbj69HG5Q15RpOKJSQwpL+iGloIUTibaWzF/LcK11wj2cJnk2JSfj7NxzAg9DcDNdsx0hO44hZyqR1Irk74RaifdPadoWRpSLCU1jwA9YYqHSQopafYEDZC5aIxJUN8sUUBo+78QZzOWnqhhtGbqVA0=,iv:43YQzZv9KMAlCu1dp3AM+BCEWYcHxFjy4/ys4lLtEo8=,tag:03jI4OUmrndUK8I4HZelsA==,type:str]
    version: 3.13.2
