apiVersion: v1
kind: Secret
metadata:
    name: synapse-admin-account
    namespace: r16a-chat
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:LMnnzIK+,iv:cglsukFD5KdvVKZsDR6Hnne2jttY2DodKboEx0EXAyQ=,tag:SJtDbok12r+66v/2JiZjmQ==,type:str]
    password: ENC[AES256_GCM,data:OszccqB+3ulnnCchYcX5kvjjWeOEtqI=,iv:/206iav65Z1FtBCpj4hpgdWpFsMMCReJyyQ0qe/rffA=,tag:NjhE3olE4ugsYE5KNWEO2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpL3BGV2Q4aUxPZHdZRzAr
            UmN4WlMvUWpwZHZJU1RBNll4QmY5UkJPdVN3CmVrQVMySkY3a1pqcFVKTkpSRzdn
            b2xSTENtd2s2eWVwUVNQRksxOXZIQjQKLS0tIFJaNzNXOVM2NFAyV2d3K3lpUi9Y
            SVdtNk5qZWJEaStmalcrZEhNWitXc3MKvcPzmRe/8lf8G7YSQQnuEy99lIZWrYYf
            fV/4n05xgL+LQ2LEuwyCHkiA4/rtJiswjiiZ7m5NuhGWzzHvCzdGNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lgkgdrmkprkm3325ufhmd64sqgc633p069xpjrngyy4ecgrzspys407msz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T11:09:53Z"
    mac: ENC[AES256_GCM,data:zTrBRyvOFfVDctpN67hKp4jNDJNnNmEzWqMzmuAEVXoL+TdHe7SA5/fX1T056AubPDsDeV+b0+rYBZWmuEjL0h8Shv8ST2swddW4AtF/96bSo1X0eMTkoCsAbjXLVUREvmzLKwTpvaUNQbVd+5ZHDu6EOyXX/gts+ujIVurKP9E=,iv:EcfTm3nKl+yIhxp+MmXSI297QJEMcw606kRnCzYVfbE=,tag:BWHYFaQW0sa1xaLWT6QpOQ==,type:str]
    version: 3.13.2
