apiVersion: v1
kind: Secret
metadata:
    name: synapse-log-config
    namespace: r16a-chat
type: Opaque
stringData:
    chat.r16a.cloud.log.config: ENC[AES256_GCM,data:4U+jNTUXukSAih6HISlDVReNFnvqxDeuYFf7iuusonRTf3As3yYqIPeWJ8yVdy8+dQGK/xFMBDuvCGFTEuqGhbdVG8QXnG7G4TnJmmZ8uxfc9WKOD2K61PFxV2/dNx7dbNwYBHPaEE7e53VMyrg7VJPUp1INwxRIyqZ+sNWwWCPHUJBgKeDHU0FbsH1zw3zFAg+s3UDf7/0xCGqNjkZA81m2hCfmmX38/VuANMf2YXyOgLkb8+ae4B6zyF7QejBI5jcPjWfIkKKcRhnJG6F4qNfvZl6A4cG51pfFSbbSs2pc6AC2Y5K9aMxaGfyMr7iYUsbjHsLX0wzTX91MMMdy9gQIhB6O8KTw4f4gLQ1vMMsM0CDGtegF8cXDkVkWqwW6u+R/bNr8alBuaX6q0gPv7CQ76I1cPWAy,iv:L4Dpg9EnLjIr0my02A1C7uiEYv3VsqTw/8PFpsQksaU=,tag:ilGCDsbsWgWvJCByqWI2Gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Y2FpckE1TFRocDBwS2ZF
            VXhXTElWQTM1c3kwYng2R2krYm9SSENESEVzCkRvSmxkNi9ZVFU5QTk1TlhuSW9k
            SlRvSlpDSklUcTRGMDlnL0l5ODNSZVEKLS0tIHhacks5b1ltS1JsNkVjaWZWR0E3
            QThtWk1Pd01lbEtjbzBWUTVyV200YmcKlkKF6zm+6iCVH+b9ByCeJ9NZaRFwqah+
            cora9oBMieM1ftp4F9pP0kIPN58uV+BIFRpztZfV8kC/qvbMZWlL+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lgkgdrmkprkm3325ufhmd64sqgc633p069xpjrngyy4ecgrzspys407msz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T12:27:36Z"
    mac: ENC[AES256_GCM,data:mcET1Yc9rLfkt8QzNpd1e5Tdf8Kk3W8Tv/T3Dd/3EO1VA5tKIzwjKSyUNmRkOu4I5/Ul5VZGEJfr54wrlUGMX8h5IKCAlIj+SZmxpQ8uxRs4SAr8wW5JkTWeugmtV8Kaxd0wUGKQSxHtdgEei6MJioPSEKXnR0R5A9bf1S03RpY=,iv:AB2J9xNd4pwtWjCT+QRXdgwqgdPcgw8HS4YIPgn216s=,tag:ZEmQZTidyps84yD0yVO4Nw==,type:str]
    version: 3.13.2
