apiVersion: v1
kind: Secret
metadata:
    name: postgres-admin
    namespace: r16a-chat
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:2v/DBWR7Fcn9nL13qrQsSQ==,iv:+RVD57bH9Vi3j502GKvUCZeP8G+2HDp6thdBYJflC1Q=,tag:/XK69R0wZytv4v7WPiQOXQ==,type:str]
    password: ENC[AES256_GCM,data:2B+lDP252celSeWBGD/1Z02oxI9T0ncyC08YZSGa+KnUF0OhCaI39qx86nY=,iv:pipAQtj0TDv1Hp+h96MM+rgQM3X0V5Xc/3v8yUMkS1s=,tag:UYxYavG7c23vKrLlN7GHpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNTcrc2JmWGQxVzFmMDJJ
            TGl5NFYzRWR0UVZ0Tk8zT29vWnBQYVBSVkVRCkxJOGNtaHN0aWpQaFA5OVhsMGlF
            a1I4VXQrdzFrZ25vZStjMFZFVTM2RzAKLS0tIHVZbTlOZEVGa0c3TFBKNnZzVkU3
            dDlXSUI3aWNhTEIxY1IwajNPWktMOEkKMbcbElDrQQP57HIkf31omCIPMccFPyXY
            mXk88XOqYqnxdFc2hwgNAMunSuF5NOJMqYu3rkCwkI1qbelQzQPFXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lgkgdrmkprkm3325ufhmd64sqgc633p069xpjrngyy4ecgrzspys407msz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T11:09:53Z"
    mac: ENC[AES256_GCM,data:kSUoeHIR4xkqiSpTFZg9ZKsk9UMj9ygQG03TRhahJy5gQJN6WHwAxUj+Iz8EhQ6cMfrjGJW9c6JIYHdWAzoQFMZDp9ztRbIc20f12VSd3R9D0fGzw9BbjWlDTTvPAsUQNpfTr2xAJdTx2uI2kkodt2J1gNhVv2rxKuJM8UI9s78=,iv:1GLiyW12XaYxk25EJj8ftb8Qh3VpCUYEfD04Pd5U/Zk=,tag:QkbG56NybI4KkTv2yVtvtw==,type:str]
    version: 3.13.2
