apiVersion: v1
kind: Secret
metadata:
    name: synapse-db
    namespace: r16a-chat
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:fCf9VQkQ5g1ICcymbdDbADtu4gG4hLEPb69wO+eqqNL6/v/WhPhTdEU6gzQ=,iv:M5H1SqFb9+rJc2BOFrFErXfTsHg4oxpH5ZyrWYYXSgg=,tag:jJHU85umkeqDPmT5kVFmZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbTF1NTRGbHQyZ2RTU05Y
            bG8yZTlmc2RjNXcyVDgrSHQ4WW1VZFpjN3lZCkszeGFWSVA0VDVkbjZ3eUVlTkli
            L0c1SkEzVnBvdHJUbXVIaTRFckRmZEEKLS0tIElrdjc1cWVqVWw5Ykw2M05wM3BF
            Y2pEcisrSDFzZVNEeFJycWNDMkEybTgK9bbPGmfTudzbBvFHsROv5Ou2U5HLTyrf
            p7v9FxEGZpQBoBBaXxQeMlugKFiziKxLPvWHL2ZhvLPI8daO1Dq2QA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lgkgdrmkprkm3325ufhmd64sqgc633p069xpjrngyy4ecgrzspys407msz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T13:15:26Z"
    mac: ENC[AES256_GCM,data:/TdyXSGVGzu0D6LzM+J7a79tbTwmNAgkBBGNE3OVDPatmSqsXIwqTn0PlC7qRzGVmRGQo9YWq4WlTids2htl0J0C98KJM4p7kMEM4Nhbc4kdedUDO6ZeI1uSCVFDH3iUYEb5pSPyoLZdPYhy5BfTHTVYgooDIV8JF0Y7pY7Xubo=,iv:tf6li1K/8q/69IyJJ5Rv6l5FfVwdqca3oMT0HOp8HtY=,tag:oL9QTduotcLglX6QNT69Eg==,type:str]
    version: 3.13.2
