apiVersion: v1
kind: Secret
metadata:
    name: synapse-db
    namespace: r16a-chat
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:klH5YaohzYTbS35P8xcd7uwGkOVG+TXbGloYZlfTCRjyry06P+dx8CcstFs=,iv:mrXReSUEfcTsZcskMbuZLXQhekcdOrLL0UU23RfcDV4=,tag:FsxBVfB/kVS2J45iF3Atgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFamVtdHJlajdzc3lhTUtD
            U2JSbDd5ckMrNGp3ckVXa1AvUzExSlFkUzNvCllpT1RtYWdMUFhWMHdGdnAva0VF
            S3VUTzV2NGtCd0FVUy9CeDRkSWJzM1kKLS0tIE1leVIrcGN1TThrMTgvVCtNNU9h
            Rmd5cVMvazU5RHBrWDBUckVPYjlTUHMKob//AJhYxe2ts6dKNj645vUbM3Xfk22i
            okBAMxQrvNC0GC+yCCGUD9rFb46/Uf+neBcMJ52QPsmn3p9HLxE7rQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lgkgdrmkprkm3325ufhmd64sqgc633p069xpjrngyy4ecgrzspys407msz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T11:09:53Z"
    mac: ENC[AES256_GCM,data:xl8IuaF0soUNG/f/zAqGyizo7+++mnIf4+BwA+OXmuOqGaWhMDo8RgDDKO1BL3LKKDvuXYsx3i3jL4NJgz1ag0rGts0R6Jh6tuCBiOozSxtruQdmJmMWbe2uHD65MfpItfi8NRiqw6J9Qaixbh0XwBNI6yWqJFhi/T4N9gzj/X4=,iv:j2joP8qSbTldU/sMrB3bcQMvWG7PoVP6fa896t4IJtI=,tag:JbNX8L9k3VrnSq+AAleOEA==,type:str]
    version: 3.13.2
