apiVersion: batch/v1
kind: Job
metadata:
  name: synapse-db-init
  namespace: r16a-chat
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: postgres:16-alpine
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 999
            capabilities:
              drop: ["ALL"]
          env:
            - name: HOME
              value: /tmp
            - name: PGHOST
              value: "postgres.r16a-databases.svc.cluster.local"
            - name: PGDATABASE
              value: "postgres"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: password
            - name: SYNAPSE_PW
              valueFrom:
                secretKeyRef:
                  name: synapse-db
                  key: password
          command: ["psql", "-f", "/sql/init.sql"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: init-sql
              mountPath: /sql
      volumes:
        - name: tmp
          emptyDir: {}
        - name: init-sql
          configMap:
            name: synapse-db-init-sql